### ISSUE TITLE
Add rustfmt config file

### ISSUE THREAD

**Issue by liss-h** [dice-group/tentris-cpp-coding-guidelines#13]
The following content should be sufficient for now:
```toml
imports_granularity = "Crate"
max_width = 120
struct_lit_width = 70
match_block_trailing_comma = true
```

It should be automatically downloaded for all our projects using rust.

I've looked up where the file is supposed to be placed (TLDR same place where we put the clang files): ["You can create a TOML file called `.rustfmt.toml`, place it in the project or any other parent directory and it will apply the options in that file."](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)
